### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by euclidian** [euclidian/rancher-rbac#2]
- Admin only
   - create migration in tbl users (`is_admin`)
- Can generate token

**Comment by euclidian** [comment]
move it to https://github.com/euclidian/user-management/issues/1

**Comment by euclidian** [comment]
bikinnya pake package ya

**Comment by yunitanurjanah** [comment]
baik mas, untuk ini apinya saja atau plus tampilan ya ?

**Comment by euclidian** [comment]
sama tampilan. Pake yang biasa dipake aja
